
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AT = 16;
  public static final int DOUBLEDOT = 96;
  public static final int IDENTIFIER = 104;
  public static final int GT = 88;
  public static final int LIMITED = 39;
  public static final int ARROW = 95;
  public static final int TYPE = 69;
  public static final int SUBTYPE = 64;
  public static final int ALIASED = 12;
  public static final int LEFTLABEL = 99;
  public static final int RAISE = 54;
  public static final int GET = 3;
  public static final int RENAMES = 58;
  public static final int UNTIL = 70;
  public static final int ASSIGNMENT = 98;
  public static final int ELSIF = 27;
  public static final int COMMA = 84;
  public static final int TERMINATE = 67;
  public static final int LT = 89;
  public static final int ALL = 13;
  public static final int INTEGER = 5;
  public static final int DECLARE = 21;
  public static final int ABORT = 7;
  public static final int PUT = 2;
  public static final int ACCESS = 11;
  public static final int LOOP = 40;
  public static final int PROTECTED = 53;
  public static final int OUT = 48;
  public static final int INTEGER_LITERAL = 105;
  public static final int NOT = 43;
  public static final int TASK = 66;
  public static final int ARRAY = 15;
  public static final int FLOAT = 6;
  public static final int THEN = 68;
  public static final int GOTO = 35;
  public static final int PACKAGE = 49;
  public static final int RECORD = 56;
  public static final int REVERSE = 61;
  public static final int BOOLEAN_LITERAL = 109;
  public static final int MOD = 41;
  public static final int WHEN = 72;
  public static final int OR_ELSE = 103;
  public static final int GENERIC = 34;
  public static final int DIGITS = 24;
  public static final int MULTIPLY = 80;
  public static final int SELECT = 62;
  public static final int OTHERS = 47;
  public static final int ABSTRACT = 9;
  public static final int VERTICAL_LINE = 94;
  public static final int PLUS = 82;
  public static final int DIVIDE = 81;
  public static final int EQUAL = 90;
  public static final int RIGHTPAR = 79;
  public static final int WHILE = 73;
  public static final int USE = 71;
  public static final int INEQUALITY = 91;
  public static final int AND_THEN = 102;
  public static final int BOOLEAN = 4;
  public static final int DO = 25;
  public static final int FOR = 32;
  public static final int CONCATENATE = 76;
  public static final int RETURN = 60;
  public static final int DELAY = 22;
  public static final int ELSE = 26;
  public static final int GTEQ = 92;
  public static final int POINT = 85;
  public static final int PROCEDURE = 52;
  public static final int ENTRY = 29;
  public static final int DELTA = 23;
  public static final int PRAGMA = 50;
  public static final int STRING_LITERAL = 108;
  public static final int TICK = 77;
  public static final int NULL = 44;
  public static final int BOX = 101;
  public static final int SEMICOLON = 87;
  public static final int EOF = 0;
  public static final int FUNCTION = 33;
  public static final int RIGHTLABEL = 100;
  public static final int MINUS = 83;
  public static final int LEFTPAR = 78;
  public static final int IS = 38;
  public static final int CONSTANT = 20;
  public static final int LTEQ = 93;
  public static final int BODY = 18;
  public static final int ACCEPT = 10;
  public static final int IN = 37;
  public static final int OR = 46;
  public static final int error = 1;
  public static final int EXIT = 31;
  public static final int IF = 36;
  public static final int OF = 45;
  public static final int ABS = 8;
  public static final int END = 28;
  public static final int COLON = 86;
  public static final int REM = 57;
  public static final int REQUEUE = 59;
  public static final int SEPARATE = 63;
  public static final int CHARACTER_LITERAL = 107;
  public static final int BEGIN = 17;
  public static final int CASE = 19;
  public static final int EXCEPTION = 30;
  public static final int NEW = 42;
  public static final int TAGGED = 65;
  public static final int EXPONENTIATE = 97;
  public static final int RANGE = 55;
  public static final int AND = 14;
  public static final int PRIVATE = 51;
  public static final int WITH = 74;
  public static final int XOR = 75;
  public static final int FLOATING_POINT_LITERAL = 106;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PUT",
  "GET",
  "BOOLEAN",
  "INTEGER",
  "FLOAT",
  "ABORT",
  "ABS",
  "ABSTRACT",
  "ACCEPT",
  "ACCESS",
  "ALIASED",
  "ALL",
  "AND",
  "ARRAY",
  "AT",
  "BEGIN",
  "BODY",
  "CASE",
  "CONSTANT",
  "DECLARE",
  "DELAY",
  "DELTA",
  "DIGITS",
  "DO",
  "ELSE",
  "ELSIF",
  "END",
  "ENTRY",
  "EXCEPTION",
  "EXIT",
  "FOR",
  "FUNCTION",
  "GENERIC",
  "GOTO",
  "IF",
  "IN",
  "IS",
  "LIMITED",
  "LOOP",
  "MOD",
  "NEW",
  "NOT",
  "NULL",
  "OF",
  "OR",
  "OTHERS",
  "OUT",
  "PACKAGE",
  "PRAGMA",
  "PRIVATE",
  "PROCEDURE",
  "PROTECTED",
  "RAISE",
  "RANGE",
  "RECORD",
  "REM",
  "RENAMES",
  "REQUEUE",
  "RETURN",
  "REVERSE",
  "SELECT",
  "SEPARATE",
  "SUBTYPE",
  "TAGGED",
  "TASK",
  "TERMINATE",
  "THEN",
  "TYPE",
  "UNTIL",
  "USE",
  "WHEN",
  "WHILE",
  "WITH",
  "XOR",
  "CONCATENATE",
  "TICK",
  "LEFTPAR",
  "RIGHTPAR",
  "MULTIPLY",
  "DIVIDE",
  "PLUS",
  "MINUS",
  "COMMA",
  "POINT",
  "COLON",
  "SEMICOLON",
  "GT",
  "LT",
  "EQUAL",
  "INEQUALITY",
  "GTEQ",
  "LTEQ",
  "VERTICAL_LINE",
  "ARROW",
  "DOUBLEDOT",
  "EXPONENTIATE",
  "ASSIGNMENT",
  "LEFTLABEL",
  "RIGHTLABEL",
  "BOX",
  "AND_THEN",
  "OR_ELSE",
  "IDENTIFIER",
  "INTEGER_LITERAL",
  "FLOATING_POINT_LITERAL",
  "CHARACTER_LITERAL",
  "STRING_LITERAL",
  "BOOLEAN_LITERAL"
  };
}

